# Generated by Django 6.0.2 on 2026-03-14 14:15

import django.db.models.deletion
import website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='frete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='categoria',
            field=models.CharField(choices=[('eletronicos', 'Eletronicos'), ('roupas', 'Roupas'), ('veiculos', 'Veiculos'), ('outros', 'Outros'), ('servicos', 'Servicos')], max_length=100),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='foto',
            field=models.ImageField(upload_to=website.models.caminho_produto),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transacao', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='pendente', max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
