# Generated by Django 6.0.2 on 2026-03-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_subscricao_verificacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificacao',
            old_name='usuario',
            new_name='user',
        ),
    ]
