# Generated by Django 6.0.2 on 2026-03-15 15:29

import django.utils.timezone
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_usuario_verificacao_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='transacao',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='foto',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=website.models.caminho_pagamento),
            preserve_default=False,
        ),
    ]
