# Generated by Django 6.0.2 on 2026-03-15 16:00

import django.utils.timezone
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_usuario_pagamento_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscricao',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AddField(
            model_name='subscricao',
            name='foto',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=website.models.caminho_plano),
            preserve_default=False,
        ),
    ]
