# Generated by Django 6.0.2 on 2026-03-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_usuario_subscricao_user_subscricao_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscricao',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificacao',
            name='fotofrente',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificacao',
            name='fotoverso',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificacao',
            name='rosto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
